---
# Homepage Admin Settings Configuration
title: Specter Realm
description: McCleaton Family Portal

background:
  image: /images/background_admin.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 75 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

quicklaunch: true
layout:
    Infrastructure:
        style: row
        columns: 4
    Security:
        style: row
        columns: 4
    DNS:
        style: row
        columns: 4
    Dashboards:
        style: row
        columns: 4
    Stream:
        style: row
        columns: 4
    ESport:
        style: row
        columns: 4
